/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.utsaditya;

import javax.swing.JOptionPane;

/**
 *
 * @author abfir
 */
public class UTS extends javax.swing.JFrame {

    /**
     * Creates new form UTS
     */
    public UTS() {
        initComponents();
        javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();
        group.add(rupiah);
        group.add(liter);

        // Set kondisi awal
        tfRupiah.setEnabled(false);
        spinnerliter.setEnabled(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jenisbbm = new javax.swing.JComboBox<>();
        tfhargasatuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rupiah = new javax.swing.JRadioButton();
        liter = new javax.swing.JRadioButton();
        spinnerliter = new javax.swing.JSpinner();
        tfRupiah = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        proses = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Jenis BBM");

        jenisbbm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih ", "Pertamax", "Pertamax Dex", "Pertalite", "Solar", "Bio Solar", " " }));
        jenisbbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisbbmActionPerformed(evt);
            }
        });

        tfhargasatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargasatuanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Rp.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("/liter");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Beli Berdasarkan");

        rupiah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rupiah.setText("Rupiah");
        rupiah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rupiahActionPerformed(evt);
            }
        });

        liter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        liter.setText("Liter");
        liter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Diskon 0%");

        proses.setBackground(new java.awt.Color(0, 204, 0));
        proses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jLabel6.setText("0");

        jLabel7.setText("10");

        jLabel8.setText("20");

        jLabel9.setText("30");

        jLabel10.setText("40");

        jLabel11.setText("50");

        jLabel12.setText("60");

        jLabel13.setText("70");

        jLabel14.setText("80");

        jLabel15.setText("90");

        jLabel16.setText("100");

        jLabel17.setText("%");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(liter)
                                    .addComponent(rupiah)
                                    .addComponent(jLabel5)
                                    .addComponent(proses))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jenisbbm, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spinnerliter)
                                            .addComponent(tfRupiah))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfhargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel17))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel10)
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16)
                                                .addGap(12, 12, 12)))
                                        .addGap(0, 21, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisbbm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfhargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rupiah)
                    .addComponent(tfRupiah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liter)
                    .addComponent(spinnerliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(proses)
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisbbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisbbmActionPerformed
  String jenis = (String) jenisbbm.getSelectedItem();
    double harga = 0;

    switch (jenis) {
        case "Pertamax":
            harga = 13250;
            break;
        case "Pertamax Dex":
            harga = 15000;
            break;
        case "Pertalite":
            harga = 10000;
            break;
        case "Solar":
            harga = 8000;
            break;
        case "Bio Solar":
            harga = 6000;
            break;
        default:
            tfhargasatuan.setText("");
            return;
    }
    tfhargasatuan.setText(String.valueOf(harga));        
    }//GEN-LAST:event_jenisbbmActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String jenis = (String) jenisbbm.getSelectedItem();
        double hargaPerLiter;

        if (jenis.contains("Pertamax")) hargaPerLiter = 13250;
        else if (jenis.contains("Pertamax Dex")) hargaPerLiter = 15000;
        else if (jenis.contains("Pertalite")) hargaPerLiter = 10000;
        else if (jenis.contains("Solar")) hargaPerLiter = 8000;
        else if (jenis.contains("Bio Solar")) hargaPerLiter = 6000;
        else {
            jTextArea.setText("Silakan pilih jenis BBM.");
            return;
        }

        int diskon = jSlider1.getValue();
        jLabel5.setText("Diskon " + diskon + "%");

        double totalHarga = 0;
        double totalLiter = 0;

        try {
            if (rupiah.isSelected()) {
                double uang = Double.parseDouble(tfRupiah.getText());
                totalLiter = uang / hargaPerLiter;
                totalHarga = uang;
            } else if (liter.isSelected()) {
                int literVal = (int) spinnerliter.getValue();
                totalLiter = literVal;
                totalHarga = literVal * hargaPerLiter;
            } else {
                jTextArea.setText("Pilih metode pembelian terlebih dahulu.");
                return;
            }
        } catch (NumberFormatException e) {
            jTextArea.setText("Input tidak valid.");
            return;
        }

        double totalDiskon = totalHarga * diskon / 100;
        double totalBayar = totalHarga - totalDiskon;

        String hasil = "Jenis BBM: " + jenis + "\n"
                     + "Harga per liter: Rp " + hargaPerLiter + "\n"
                     + "Jumlah liter: " + String.format("%.2f", totalLiter) + " L\n"
                     + "Total harga sebelum diskon: Rp " + totalHarga + "\n"
                     + "Diskon: " + diskon + "% (Rp " + totalDiskon + ")\n"
                     + "Total bayar: Rp " + totalBayar;

        jTextArea.setText(hasil);
        JOptionPane.showMessageDialog(this,hasil,"DATA PEMBELI",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_prosesActionPerformed

    private void rupiahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rupiahActionPerformed
    tfRupiah.setEnabled(true);
    tfRupiah.setText(""); // Kosongkan input rupiah saat diaktifkan
    spinnerliter.setEnabled(false);
    spinnerliter.setValue(0); // Reset nilai spinner

    }//GEN-LAST:event_rupiahActionPerformed

    private void literActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literActionPerformed
    tfRupiah.setEnabled(false);
    tfRupiah.setText(""); // Kosongkan input rupiah karena tidak digunakan
    spinnerliter.setEnabled(true);
    spinnerliter.setValue(0); // Reset nilai spinner saat diaktifkan
    }//GEN-LAST:event_literActionPerformed

    private void tfhargasatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargasatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargasatuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JComboBox<String> jenisbbm;
    private javax.swing.JRadioButton liter;
    private javax.swing.JButton proses;
    private javax.swing.JRadioButton rupiah;
    private javax.swing.JSpinner spinnerliter;
    private javax.swing.JTextField tfRupiah;
    private javax.swing.JTextField tfhargasatuan;
    // End of variables declaration//GEN-END:variables
}
