/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProgramBensin;

/**
 *
 * @author abfir
 */
import javax.swing.*;

public class ProgramBensin extends javax.swing.JFrame {
private ButtonGroup grupBeli;


    
        public ProgramBensin() {
        initComponents();
        setupButtonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jenisbensin = new javax.swing.JComboBox<>();
        tfharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rupiah = new javax.swing.JRadioButton();
        liter = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        proses = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfRpliter = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PERTAMINA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Jenis Bensin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("HargaPerliter");

        jenisbensin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pertalite-Rp.10.000", "Pertamax-Rp.13.500", "Solar-Rp.6.800" }));
        jenisbensin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisbensinActionPerformed(evt);
            }
        });

        tfharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Beli Berdasarkan :");

        rupiah.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        rupiah.setText("Rupiah");
        rupiah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rupiahActionPerformed(evt);
            }
        });

        liter.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        liter.setText("Liter");
        liter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        proses.setBackground(new java.awt.Color(0, 153, 51));
        proses.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Rp.");

        tfRpliter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRpliterActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 51, 153));
        reset.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(102, 0, 0));
        exit.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(rupiah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(liter)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(137, 137, 137))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenisbensin, 0, 162, Short.MAX_VALUE)
                            .addComponent(tfharga)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(tfRpliter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(proses)
                                .addGap(27, 27, 27)
                                .addComponent(reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exit))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisbensin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rupiah)
                    .addComponent(liter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfRpliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proses)
                    .addComponent(reset)
                    .addComponent(exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargaActionPerformed

    private void rupiahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rupiahActionPerformed
        // TODO add your handling code here:
        tfRpliter.setEnabled(true);
        tfRpliter.setText("");
    }//GEN-LAST:event_rupiahActionPerformed

    private void jenisbensinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisbensinActionPerformed
        // TODO add your handling code here:
        String pilihan = jenisbensin.getSelectedItem().toString();
        if (pilihan.contains("Pertalite")) {
            tfharga.setText("10000");
        } else if (pilihan.contains("Pertamax")) {
            tfharga.setText("13500");
        } else if (pilihan.contains("Solar")) {
            tfharga.setText("6800");
        }

    }//GEN-LAST:event_jenisbensinActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
             try {
        String jenisBensin = jenisbensin.getSelectedItem().toString();
        double hargaPerLiter = Double.parseDouble(tfharga.getText());
        
        // Mengecek apakah user memilih satu metode (Rupiah atau Liter)
        if (!rupiah.isSelected() && !liter.isSelected()) {
            jTextPane1.setText("Silakan pilih metode pembelian terlebih dahulu!");
            return;
        }

        double inputJumlah = Double.parseDouble(tfRpliter.getText());
        String hasil = "";

        if (rupiah.isSelected()) {
            // Jika beli berdasarkan Rupiah
            double literDidapat = inputJumlah / hargaPerLiter;
            hasil += "Jenis Bensin: " + jenisBensin + "\n";
            hasil += "Harga per Liter: Rp " + hargaPerLiter + "\n";
            hasil += "Beli berdasarkan: Rupiah\n";
            hasil += "Jumlah Uang: Rp " + inputJumlah + "\n";
            hasil += "Total Liter: " + String.format("%.2f", literDidapat) + " L";
        } else if (liter.isSelected()) {
            // Jika beli berdasarkan Liter
            double totalHarga = inputJumlah * hargaPerLiter;
            hasil += "Jenis Bensin: " + jenisBensin + "\n";
            hasil += "Harga per Liter: Rp " + hargaPerLiter + "\n";
            hasil += "Beli berdasarkan: Liter\n";
            hasil += "Jumlah Liter: " + inputJumlah + " L\n";
            hasil += "Total Harga: Rp " + String.format("%.2f", totalHarga);
        }

        jTextPane1.setText(hasil);

    } catch (NumberFormatException e) {
        jTextPane1.setText("Input salah! Pastikan angka yang dimasukkan valid.");
    } catch (Exception e) {
        jTextPane1.setText("Terjadi kesalahan: " + e.getMessage());
    }
        
    }//GEN-LAST:event_prosesActionPerformed
private void setupButtonGroup() {
        grupBeli = new ButtonGroup();
        grupBeli.add(rupiah);
        grupBeli.add(liter);
    }

    private void tfRpliterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRpliterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRpliterActionPerformed

    private void literActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literActionPerformed
        // TODO add your handling code here:
        tfRpliter.setEnabled(true);
        tfRpliter.setText("");

    }//GEN-LAST:event_literActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
            jenisbensin.setSelectedIndex(0);
            tfharga.setText("");
            tfRpliter.setText("");
            jTextPane1.setText("");
            grupBeli.clearSelection();
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramBensin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramBensin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramBensin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramBensin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramBensin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox<String> jenisbensin;
    private javax.swing.JRadioButton liter;
    private javax.swing.JButton proses;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton rupiah;
    private javax.swing.JTextField tfRpliter;
    private javax.swing.JTextField tfharga;
    // End of variables declaration//GEN-END:variables

   // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

